[pytest]
norecursedirs = venv* docs *.egg-info .git dlio_benchmark data checkpoints build hydra_log 
filterwarnings =
	ignore:This process \(pid=.*\) is multi-threaded, use of fork\(\) may lead to deadlocks in the child:DeprecationWarning:multiprocessing\.popen_fork